server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Angular SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Prometheus stub_status (allow pod & cluster)
    location /stub_status {
        stub_status on;
        allow all;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|gif|ico|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
